### ISSUE TITLE
Inconsistent row number among input bed, features and genotype

### ISSUE THREAD

**Issue by HelloYanming** [parklab/MosaicForecast#41]
Hi,

Thanks for making this wonderful tool. However, I am wondering if it is normal to see decrease on the count from input bed file to features to genotypes. For example, there are 742544 rows in my input bed, and it decreased to 601663 in my feature output and finally 428451 in genotype output. It is understandable there are filters in the feature step, but I am not sure why the genotype output has fewer rows than feature output.

**Comment by douym** [comment]
Dear @HelloYanming ,

Thanks for using MosaicForecast and sorry for the delayed response. The number of rows decreased because when some features could not be computed (i.e., this occurs when there are not enough reads to calculate p-values of rank sum test), I simply discard the rows. Your suggestion is great, I could probably retain the rows and mark the site as "NA" in the next version of MosaicForecast. 

Best wishes,

Yanmei
